spring:
  application:
    name: demo-service
  profiles:
    active: dev
server:
  port: ${server-port:9001}
  compression:
    enabled: true
    mime-types: textml,text/xml,text/plain,application/json,application/xml
#  tomcat:
#    accesslog:
#      enabled: true
#      basedir: /logs
#      pattern: '%h %l %u %t "%r" %s %b %D'
#      prefix: access_log
#      directory: /logs
