spring:
  datasource:
    url: jdbc:mysql://${mysql_host:localhost}:${mysql_port:3306}/${mysql_dbname:test}?charset=utf8
    username: ${mysql_username:root}
    password: ${mysql_password:123456}
    driver-class-name: com.mysql.jdbc.Driver


# mybatis 配置
mybatis:
  config-location: classpath:mybatis-config.xml

#es 配置
es:
  elasticsearch:
    clusterNodes: ${es_nodes:http://127.0.0.1:9200}



logging:
  level:
    root: info







